export type Happi123Metadata = {
  singer?: string
  composer?: string
  lyricist?: string
}

// Only include attributions that identify the underlying work unambiguously.
const metadataByTitle: Record<string, Happi123Metadata> = {
  '第二圆舞曲': { composer: '德米特里·肖斯塔科维奇' },
  '卡农': { composer: '约翰·帕赫贝尔' },
  '土耳其进行曲': { composer: '莫扎特' },
  '西西里': { composer: '加布里埃尔·福雷' },
  '遇见': { composer: '林一峰', lyricist: '易家扬' },
  '小星星': { composer: '传统法国民歌' },
  '苏珊娜': { composer: '斯蒂芬·福斯特' },
  '爱尔兰画眉': { composer: '传统爱尔兰民歌' },
  '欢乐颂': { composer: '路德维希·范·贝多芬' },
  '送别': { composer: '约翰·P·奥德韦', lyricist: '李叔同' },
  '虫儿飞': { composer: '陈光荣', lyricist: '林夕' },
  '痴情冢': { composer: '谭旋', lyricist: '张赢' },
  '小红帽': { composer: '传统巴西民歌' },
  '红河谷': { composer: '传统加拿大民歌' },
  '喀秋莎': { composer: '马特维·勃兰切尔', lyricist: '米哈伊尔·伊萨科夫斯基' },
  '三套车': { composer: '俄罗斯民歌' },
  '倩女幽魂': { composer: '黄霑', lyricist: '黄霑' },
  '后来': { composer: '玉置浩二', lyricist: '施人诚' },
  '贝加尔湖畔': { composer: '李健', lyricist: '李健' },
  '过火': { composer: '曹俊鸿', lyricist: '厉曼婷' },
  '当年情': { composer: '顾嘉辉', lyricist: '黄霑' },
  '月半小夜曲': { composer: '河合奈保子', lyricist: '向雪怀' },
  '漫步人生路': { composer: '中岛美雪', lyricist: '郑国江' },
  '童话镇': { composer: '暗杠', lyricist: '竹君' },
  '一步之遥': { composer: '阿斯托尔·皮亚佐拉' },
  '美丽的神话': { composer: '王力宏', lyricist: '王中言' },
  'New Boy': { composer: '朴树', lyricist: '朴树' },
  '黄昏': { composer: '周传雄', lyricist: '陈信荣' },
  '听海': { composer: '涂惠源', lyricist: '林秋离' },
  '我的祖国': { composer: '刘炽', lyricist: '乔羽' },
  '我和我的祖国': { composer: '秦咏诚', lyricist: '张藜' },
  '月亮代表我的心': { composer: '翁清溪', lyricist: '孙仪' },
  '一千个伤心的理由': { composer: '李偲菘', lyricist: '邢增华' },
  '约定': { composer: '陈小霞', lyricist: '姚若龙' },
  '直到世界的尽头': { composer: '织田哲郎', lyricist: '上杉升' },
  '只要平凡': { composer: '钱雷', lyricist: '唐恬' },
  '世界赠予我的': { composer: '曹正杰', lyricist: '袁晶' },
  '牵丝戏': { composer: '银临', lyricist: 'Vagary' },
  '相思': { composer: '三宝', lyricist: '赵国利' },
  '凉凉': { composer: '谭旋', lyricist: '刘畅' },
  '哆唻咪': { composer: '理查德·罗杰斯', lyricist: '奥斯卡·汉默斯坦二世' },
  '梁祝': { composer: '何占豪、陈钢' },
  '茉莉花': { composer: '中国民歌' },
  '很久以前': { composer: '托马斯·海恩斯·贝利' },
  '莫斯科郊外的晚上': { composer: '瓦西里·索洛维约夫-谢多伊', lyricist: '米哈伊尔·马图索夫斯基' },
  '老男孩': { composer: '大塚爱', lyricist: '王太利' },
  '友谊地久天长': { composer: '苏格兰民歌', lyricist: '罗伯特·彭斯' },
  '光阴的故事': { composer: '罗大佑', lyricist: '罗大佑' },
  '铁血丹心': { composer: '顾嘉辉', lyricist: '邓伟雄' },
  '国际歌': { composer: '皮埃尔·狄盖特', lyricist: '欧仁·鲍狄埃' },
  '明天会更好': { composer: '罗大佑', lyricist: '罗大佑' },
  '暗香': { composer: '三宝', lyricist: '陈涛' },
  '慢慢喜欢你': { composer: '李荣浩', lyricist: '李荣浩' },
  '同桌的你': { composer: '高晓松', lyricist: '高晓松' },
  '寂静之声': { composer: '保罗·西蒙', lyricist: '保罗·西蒙' },
  '如愿': { composer: '钱雷', lyricist: '唐恬' },
  '我和你': { composer: '陈其钢', lyricist: '陈其钢' },
  '让我们荡起双桨': { composer: '刘炽', lyricist: '乔羽' },
  '人世间': { composer: '钱雷', lyricist: '唐恬' },
  '白桦林': { composer: '朴树', lyricist: '朴树' },
  '超级玛丽': { composer: '近藤浩治' },
  '青鸟': { composer: '水野良树', lyricist: '水野良树' },
  '喜洋洋': { composer: '刘明源' },
  '斯卡布罗集市': { composer: '传统英格兰民歌' },
  '天空之城': { composer: '久石让' },
  '太阳照常升起': { composer: '久石让' },
  '菊次郎的夏天': { composer: '久石让' },
  '云宫迅音': { composer: '许镜清' },
  '花之舞': { composer: 'DJ OKAWARI' },
  '我只在乎你': { composer: '中岛美雪', lyricist: '慎芝' },
  '温柔的倾诉': { composer: '尼诺·罗塔', lyricist: '拉里·库西克' },
  '蜗牛与黄鹂鸟': { composer: '台湾民歌' },
  '我要你': { composer: '樊冲', lyricist: '樊冲' },
  '啤酒桶波尔卡': { composer: '雅罗米尔·韦伊沃达' },
  '哆啦A梦': { composer: '菊池俊辅', lyricist: '楠部工' },
  '红莓花儿开': { composer: '伊萨克·杜纳耶夫斯基', lyricist: '米哈伊尔·伊萨科夫斯基' },
}

export function getHappi123Metadata(title: string) {
  return metadataByTitle[title] ?? {}
}
