import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { scoreMetadataFromSource } from '../src/lib/score-metadata'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const scoresDirectory = join(projectRoot, 'src', 'scores')
const outputPath = join(scoresDirectory, 'index.ts')

const entries = await readdir(scoresDirectory, { withFileTypes: true })
const index = await Promise.all(entries
  .filter((entry) => entry.isFile() && entry.name.endsWith('.m3n'))
  .sort((left, right) => left.name.localeCompare(right.name))
  .map(async (entry) => scoreMetadataFromSource(entry.name.slice(0, -4), await readFile(join(scoresDirectory, entry.name), 'utf8'))))

const output = [
  "import type { PresetScoreMetadata } from '../lib/score-metadata'",
  '',
  '// Generated by tools/generate-score-index.ts. Do not edit manually.',
  `export const presetScoreIndex = ${JSON.stringify(index, null, 2)} as const satisfies readonly PresetScoreMetadata[]`,
  '',
].join('\n')

await writeFile(outputPath, output)
console.log(`Generated ${outputPath}`)
